name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: 17
          distribution: temurin

      - name: Build with Maven
        run: mvn clean package -DskipTests
        working-directory: ./source

      - name: Compress
        run: |
          mkdir -p ./package
          cp ./source/target/*.jar ./package/
          tar czf ./package/BoroDamn.tar.gz -C ./package .

      - name: Deploy to server
        env:
          HOST: ${{ secrets.SERVER_HOST }}
          USER: ${{ secrets.SERVER_USER }}
          KEY: ${{ secrets.SERVER_SSH_KEY }}
        run: |
          echo "$KEY" > key.pem
          chmod 600 key.pem
          scp -o StrictHostKeyChecking=no -i key.pem ./package/BoroDamn.tar.gz $USER@$HOST:/opt/BoroDamn/build/
          ssh -o StrictHostKeyChecking=no -i key.pem $USER@$HOST "
            cd /opt/BoroDamn/build &&
            tar xzf BoroDamn.tar.gz &&
            cd /opt/BoroDamn &&
            ./deploy.sh
          "
