##################### ⚙️ container configuration #####################################################
image: registry.baidubce.com/gitee_go/maven-plugin:saas-23
cpu: 2
memory: 4Gi
######################################################################################################

stages:
  - name: Build and Deploy
    steps:
      - name: Build with Maven
        script:
          # 进入 pom.xml 所在目录并构建
          - cd source
          - mvn -B clean package -Dmaven.test.skip=true

      - name: Prepare package
        script:
          - mkdir -p package
          - cp source/target/*.jar package/
          - tar czf package/BoroDamn.tar.gz -C package .

      - name: Copy jar to server
        script:
          - apt-get update && apt-get install -y openssh-client
          - echo "$SERVER_SSH_KEY" > key.pem
          - chmod 600 key.pem
          - scp -o StrictHostKeyChecking=no -i key.pem package/BoroDamn.tar.gz $SERVER_USER@$SERVER_HOST:/opt/BoroDamn/build/

      - name: Deploy on server
        script:
          - ssh -o StrictHostKeyChecking=no -i key.pem $SERVER_USER@$SERVER_HOST "
            cd /opt/BoroDamn/build &&
            tar xzf BoroDamn.tar.gz &&
            cd /opt/BoroDamn &&
            ./deploy.sh
            "
